// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcW7l9sQ743Z4CRyHsJ2buz2mCB_r3zDs',
    appId: '1:797749511608:web:c04472c87b2366780d7b4d',
    messagingSenderId: '797749511608',
    projectId: 'restaurante-c',
    authDomain: 'restaurante-c.firebaseapp.com',
    storageBucket: 'restaurante-c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAICQ6-LpaPVL9BLH-TcHIVb6-w1rWQXG4',
    appId: '1:797749511608:android:243d9407a62f2d500d7b4d',
    messagingSenderId: '797749511608',
    projectId: 'restaurante-c',
    storageBucket: 'restaurante-c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyUYjX7765kc0IqPpMHZb33fViGeb0eD0',
    appId: '1:797749511608:ios:e5d2134770de16530d7b4d',
    messagingSenderId: '797749511608',
    projectId: 'restaurante-c',
    storageBucket: 'restaurante-c.appspot.com',
    iosBundleId: 'com.example.learningc',
  );
}
